### ISSUE TITLE
README

### ISSUE THREAD

**Issue by 7yl4r** [JSilvanima/R-Club-spsurvey-and-sample-surveys#1]
It is not clear to me what the different files are in this repo and where I should start when taking a look at it. Adding a `README.md` to give a basic overview would be helpful.

**Comment by JSilvanima** [comment]
Hey Tylar,
I have added a read me file.  Hopefully this will help decipher some the files in the repo.  Thanks for point that out!

Jay


-----Original Message-----
From: Tylar ***@***.***>
To: JSilvanima/R-Club-spsurvey-and-sample-surveys ***@***.***>
Cc: Subscribed ***@***.***>
Sent: Fri, Sep 10, 2021 12:36 pm
Subject: [JSilvanima/R-Club-spsurvey-and-sample-surveys] README (#1)

It is not clear to me what the different files are in this repo and where I should start when taking a look at it. Adding a README.md to give a basic overview would be helpful.—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 7yl4r** [comment]
Thank you! That helps a lot.
